name: Continuous Integration

on:
  push:
      branches:
        main
  pull_request:
      branches:
        main

jobs:
  build-library:
    name: build library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16.x, 18.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: install dependencies
        run: npm ci
      - name: build we-select
        run: ng build we-select
      - name: run tests
        run: ng test we-select -- --watch=false --browsers=ChromeHeadless
    
