name: Continuous Integration

on:
  push:
      branches:
        main
  pull_request:
      branches:
        main

jobs:
  build-library:
    name: build library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.x, 12.x, 14.x, 16.x, 18.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: clean install
        run: npm ci
      - name: run tests
        run: npm test
    
