name: Continuous Integration

on:
  pull_request:
      branches:
        - main
        
jobs:
  build_library:
    name: build library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: install angular CLI
        run: npm install -g @angular/cli
        
      - name: install dependencies
        run: npm ci
        
      - name: build we-select
        run: ng build we-select
        
      - name: run tests
        run: ng test we-select --watch=false --browsers=ChromeHeadless

  create_tag:
    needs: build_library
    runs-on: ubuntu-latest
    steps:
      - name: git configuration
        run: |
          git config --global user.name "navenkumar"
          git config --global user.email "naven.duraisamy5859@gmail.com"
      
      - name: update version
        run: npm version ${{ github.event.inputs.version_bump }}

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags
    
